workflows:
  ios-pwa-build:
    name: iOS Development Build
    environment:
      groups:
        - ios_credentials
      ios_signing:
        distribution_type: development
        bundle_identifier: si.fynd.app
        provisioning_profiles:
          - si.fynd.app
      vars:
        XCODE_PROJECT: "fynd..xcodeproj"
        XCODE_SCHEME: "fynd."
    scripts:
      - name: Install dependencies (if applicable)
        script: |
          if [ -f "Podfile" ]; then pod install; fi
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/*.ipa