workflows:
  ios-pwa-build:
    name: fynd. iOS
    environment:
      groups:
        - ios_credentials  # Set this up in Codemagic UI with your certs
      ios_signing:
        distribution_type: app_store
        bundle_identifier: si.fynd.app  # Your app bundle ID
    scripts:
      - name: Install CocoaPods dependencies (if needed)
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build the project
        script: |
          xcode-project build-ipa \
            --project "fynd..xcodeproj" \
            --scheme "fynd." \
            --archive-path build/fynd..xcarchive \
            --export-options-plist ExportOptions.plist
    artifacts:
      - build/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
