name: iOS IPA Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up code signing
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Setup Provisioning Profile
        env:
          PROFILE_BASE64: ${{ secrets.PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/dev.mobileprovision

      - name: Build IPA
        run: |
          xcodebuild -project YourApp.xcodeproj \
            -scheme YourApp \
            -configuration Release \
            -archivePath build/YourApp.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/*.ipa
